/** The sole AIDLC public-command grammar. `scripts/aidlc.ts` renders this text. */
const aidlcCatalogSections: readonly string[] = [
  'AIDLC command catalog',
  '',
  'Replace every <placeholder> before execution. Each row is a complete command for one situation. Do not append guessed flags, omit shown arguments, use --help, or retry with altered arguments. Execute only the action returned by the previous lifecycle command.',
  '',
  'Priority 1 — start one intent from the selected project root',
  'When: A code change needs the AIDLC route and UI is not in scope.',
  'Command: bun <agents-root>/scripts/aidlc.ts start "<intent-summary>"',
  'Result: one intent path, acceptance checklist, final-gate command, and current packet.',
  'Next: establish the packet evidence, then record the returned consecutive stages.',
  '',
  'Priority 2 — start one intent with UI work',
  'When: The requested change creates, redesigns, or visually refreshes a user-facing UI.',
  'Command: bun <agents-root>/scripts/aidlc.ts start "<intent-summary>" --ui',
  'Result: the same bootstrap receipt, with the Refined Mockups stage selected.',
  'Next: establish the packet evidence, then record the returned consecutive stages.',
  '',
  'Priority 3 — start one intent with already-established Initialization evidence',
  'When: The supplied Initialization evidence is factual, consecutive, and ends at Approval Handoff.',
  'Command: bun <agents-root>/scripts/aidlc.ts start "<intent-summary>" --initial-record \'<stage-outcomes-json-array>\'',
  'Result: one intent receipt containing the persisted established evidence.',
  'Next: present the Approval Handoff; do not add invented stage evidence.',
  '',
  'Priority 4 — approve and record established post-approval evidence together',
  'When: The user explicitly approved and the KB context plus consecutive post-approval stage outcomes are already factual.',
  'Command: bun <agents-root>/scripts/aidlc.ts approve "<intent-path>" "<approval-evidence>" --context "<private-kb-root>" "<organization-concept-path-or-dash>" "<team-concept-path-or-dash>" "<project-concept-path-or-dash>" --record \'<stage-outcomes-json-array>\'',
  'Result: approval, validated KB bindings, and every supplied outcome persist atomically.',
  'Next: use only the returned next action. Do not call approve or record again for the same facts.',
  '',
  'Priority 5 — approve when post-approval evidence is not ready',
  'When: The user explicitly approved but Reverse Engineering has not yet produced factual evidence.',
  'Command: bun <agents-root>/scripts/aidlc.ts approve "<intent-path>" "<approval-evidence>"',
  'Result: approval persists and the receipt returns the Reverse Engineering packet.',
  'Next: establish evidence, then use the Priority 7 record command.',
  '',
  'Priority 6 — approve with validated KB context and no stage evidence',
  'When: The user explicitly approved, the KB bindings are known, and post-approval research is not complete.',
  'Command: bun <agents-root>/scripts/aidlc.ts approve "<intent-path>" "<approval-evidence>" --context "<private-kb-root>" "<organization-concept-path-or-dash>" "<team-concept-path-or-dash>" "<project-concept-path-or-dash>"',
  'Result: approval and context persist atomically; no research outcome is claimed.',
  'Next: establish evidence, then use the Priority 7 record command.',
  '',
  'Priority 7 — record one or more established consecutive non-gated outcomes',
  'When: Every supplied outcome is factual, consecutive, and does not cross Approval Handoff or Build and Test.',
  'Command: bun <agents-root>/scripts/aidlc.ts record "<intent-path>" \'<stage-outcomes-json-array>\'',
  'Result: each supplied stage outcome persists in one lifecycle receipt.',
  'Next: execute only the receipt action.',
  '',
  'Priority 8 — record Code Generation, run the final gate, close out without a durable lesson, and retire',
  'When: Code Generation evidence is factual and knowledge-base has already determined that no durable lesson should be captured.',
  'Command: bun <agents-root>/scripts/aidlc.ts record "<intent-path>" \'<stage-outcomes-json-array>\' --final-gate --closeout --no-durable-lesson "<knowledge-base-assessment>"',
  'Result: the single configured final gate runs; a pass persists closeout and retires the intent.',
  'Next: on failure, repair the approved change and rerun this exact command. On success, stop.',
  '',
  'Priority 9 — run the final gate, close out without a durable lesson, and retire',
  'When: Build and Test is active and knowledge-base has already determined that no durable lesson should be captured.',
  'Command: bun <agents-root>/scripts/aidlc.ts complete "<intent-path>" --closeout --no-durable-lesson "<knowledge-base-assessment>"',
  'Result: the single configured final gate runs; a pass persists closeout and retires the intent.',
  'Next: on failure, repair the approved change and rerun this exact command. On success, stop.',
  '',
  'Priority 10 — run the final gate when durable-knowledge disposition is unknown',
  'When: Build and Test is active and knowledge-base still must decide whether a durable concept is needed.',
  'Command: bun <agents-root>/scripts/aidlc.ts complete "<intent-path>"',
  'Result: the configured final gate runs once. A pass returns one KB closeout action.',
  'Next: execute only that returned action. Do not call closeout, retire, recover, or complete again on your own.',
  '',
  'Priority 11 — persist one active ordinary stage',
  'When: The current non-gated stage has one factual conclusion and no consecutive batch is available.',
  'Command: bun <agents-root>/scripts/aidlc.ts complete "<intent-path>" "<factual-evidence>"',
  'Result: exactly the active non-gated stage persists.',
  'Next: execute only the receipt action.',
  '',
  'Conditional recovery — skip one inapplicable active non-gated stage',
  'When: The returned stage is factually inapplicable.',
  'Command: bun <agents-root>/scripts/aidlc.ts skip "<intent-path>" "<factual-inapplicability-reason>"',
  'Result: one recorded skip and the next packet.',
  'Next: continue with the returned action.',
  '',
  'Conditional recovery — revise a material user-directed decision',
  'When: New user evidence changes approved scope, architecture, or a material earlier decision.',
  'Command: bun <agents-root>/scripts/aidlc.ts replan "<intent-path>" "<factual-change-evidence>"',
  'Result: a causally linked lifecycle correction.',
  'Next: use the returned packet; do not hand-edit stage state.',
  '',
  'Conditional recovery — supersede an intent',
  'When: A user-approved replacement intent supersedes the current intent.',
  'Command: bun <agents-root>/scripts/aidlc.ts supersede "<intent-path>" "<replacement-intent-id>"',
  'Result: the current intent is superseded.',
  'Next: use the replacement intent only after its own lifecycle receipt.',
  '',
  'Conditional recovery — reconcile a known intent collision',
  'When: The lifecycle runtime explicitly returns intent-reconciliation diagnostics.',
  'Command: bun <agents-root>/scripts/aidlc.ts queue "<cbm-index>"',
  'Result: diagnostic queue information only.',
  'Next: follow the returned reconciliation action; never use queue to start an intent.',
  '',
  'Conditional recovery — begin AIDLC-owned KB capture and Markdown guarding',
  'When: A bare successful final gate returned this action and a fixed capture request exists.',
  'Command: bun <agents-root>/scripts/aidlc.ts capture-and-begin "<intent-path>" "<private-kb-root>" "<absolute-capture-request-path>"',
  'Result: captured source paths, one guard session, and one finalize action.',
  'Next: edit only returned source paths, then execute the returned finalize-and-recover action.',
  '',
  'Conditional recovery — finalize the returned AIDLC KB session',
  'When: capture-and-begin returned this exact command after the permitted source edits.',
  'Command: bun <agents-root>/scripts/aidlc.ts finalize-and-recover "<intent-path>"',
  'Result: protected-token validation, KB closeout, and retirement.',
  'Next: stop on success; report the returned repair action on failure.',
  '',
  'Conditional recovery — recover a persisted closeout after interruption',
  'When: The runtime returned a recovery action after a bare final-gate pass or interrupted retirement.',
  'Command: bun <agents-root>/scripts/aidlc.ts recover "<intent-path>" --retire-only',
  'Result: an already-persisted closeout retires safely.',
  'Next: stop on success.',
  '',
  'Stage-outcomes JSON array',
  '[{"stage":"<stage-slug>","outcome":"<complete-or-skip>","evidence":"<factual-evidence>"}]',
  'Every array entry requires stage, outcome, and factual evidence. The runtime rejects unknown, nonconsecutive, gated, or duplicated outcomes.',
  '',
  'Capture-request JSON object',
  '{"relativePath":"<scope>/<subject>/<concept>.md","metadata":{"type":"<concept-type>","title":"<title>","description":"<description>","tags":["<tag>"]},"body":"<durable-markdown>","evidence":"<factual-capture-evidence>"}',
  'The request path is absolute. AIDLC owns capture, reconciliation, guarding, validation, closeout, and retirement. The assistant edits only source paths returned by capture-and-begin.',
];

export const aidlcCommandContract = (): readonly string[] =>
  aidlcCatalogSections;

export const renderAidlcCommandContract = (): string =>
  aidlcCommandContract().join('\n');
